import 'package:get/get.dart';

class MyLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome to Todozoid! Please sign in to continue.',
          'termsandconditions1': 'By signing in, you agree to our ',
          'termsandconditions2': 'terms and conditions.',
          'dashboard': 'Dashboard',
          'tasks': 'Tasks',
          'lists': 'Lists',
          'work': 'Work',
          'home': 'Home',
          'shopping': 'Shopping',
          'personal': 'Personal',
          'diary': 'Tasks diary',
          'categorieslist': 'Categories list',
          'settings': 'Settings',
          'theme': 'Theme',
          'light': 'Light',
          'dark': 'Dark',
          'review': 'Leave a review',
          'bug': 'Report a bug',
          'dailygoal': 'Daily goal',
          'noactive': 'No active tasks',
          'noactivelists': 'No active lists',
          'activetasks': 'Active tasks',
          'view': 'View',
          'thisweek': 'Tasks completed this week',
          'createTask': 'Create task',
          'updateTask': 'Update task',
          'newTaskTextField': 'New task',
          'category': 'Category',
          'day': 'Day',
          'time': 'Time',
          'selectDay': 'Select day',
          'selectTime': 'Select time',
          'note': 'Write a note...',
          'addSubtask': 'Add subtask',
          'newSubtaskTextField': 'New subtask',
          'sortByDate': 'Date',
          'sortByDescription': 'Description',
          'sortByCategory': 'Category',
          'when': 'When',
          'edit': 'Edit',
          'delete': 'Delete',
          'dateOrTime': 'Do you want to change Date or Time?',
          'changeDate': 'Change Date',
          'changeTime': 'Change Time',
          'cancel': 'Cancel',
          'createList': 'Create list',
          'updateList': 'Update list',
          'listNameTextField': 'Name new list',
          'pickIcon': 'Pick icon (optional)',
          'addItem': 'Add item',
          'open': 'Open',
          'clear': 'Clear',
          'share': 'Share',
          'today': 'Today',
          'tomorrow': 'Tomorrow',
          'overdue': 'Task is overdue',
          'remindToday': 'Remind today at ',
          'remindTomorrow': 'Remind tomorrow at',
          'at': 'at',
          'signOut': 'Sign out',
          'categoryName': 'Category name',
          'newItem': 'New item',
          'taskReminder': 'Task reminder'
        },
        'ru_RU': {
          'welcome':
              'Добро пожаловать в Todozoid! Пожалуйста, войдите, чтобы продолжить.',
          'termsandconditions1': 'Выполняя вход, вы соглашаетесь с нашими ',
          'termsandconditions2': 'условиями и положениями.',
          'dashboard': 'Дэшборд',
          'tasks': 'Задачи',
          'lists': 'Списки',
          'work': 'Работа',
          'home': 'Дом',
          'shopping': 'Покупки',
          'personal': 'Личное',
          'diary': 'Дневник задач',
          'categorieslist': 'Список категорий',
          'settings': 'Настройки',
          'theme': 'Тема',
          'light': 'Светлая',
          'dark': 'Темная',
          'review': 'Оставить отзыв',
          'bug': 'Сообщить об ошибке',
          'dailygoal': 'Дневная норма',
          'noactive': 'Нет активных задач',
          'noactivelists': 'Нет активных списков',
          'activetasks': 'Активные задачи',
          'view': 'Смотреть',
          'thisweek': 'Задач выполнено на этой неделе',
          'createTask': 'Создать задачу',
          'updateTask': 'Обновить задачу',
          'newTaskTextField': 'Новая задача',
          'category': 'Категория',
          'day': 'День',
          'time': 'Время',
          'selectDay': 'Выбрать день',
          'selectTime': 'Выбрать время',
          'note': 'Написать заметку...',
          'addSubtask': 'Добавить подзадачу',
          'newSubtaskTextField': 'Новая подзадача',
          'sortByDate': 'Дата',
          'sortByDescription': 'Описание',
          'sortByCategory': 'Категория',
          'when': 'Когда',
          'edit': 'Редак-ть',
          'delete': 'Удалить',
          'dateOrTime': 'Вы хотите поменять Дату или Время?',
          'changeDate': 'Изменить Дату',
          'changeTime': 'Изменить Время',
          'cancel': 'Отмена',
          'createList': 'Создать список',
          'updateList': 'Обновить список',
          'listNameTextField': 'Наименование списка',
          'pickIcon': 'Выбрать иконку (необязательно)',
          'addItem': 'Добавить элемент',
          'open': 'Открыть',
          'clear': 'Очистить',
          'share': 'Поделиться',
          'today': 'Сегодня',
          'tomorrow': 'Завтра',
          'overdue': 'Задача просрочена',
          'remindToday': 'Напомнить сегодня в ',
          'remindTomorrow': 'Напомнить завтра в ',
          'at': 'в',
          'signOut': 'Выйти',
          'categoryName': 'Наименование категории',
          'newItem': 'Новый элемент',
          'taskReminder': 'Напоминание о задаче'
        }
      };
}
