// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQLq3o5P3qLTjkrmj5sferhwrL7S12Is',
    appId: '1:75536888095:android:177dcafed1f59c7801802a',
    androidClientId:
        '75536888095-evs42lptg1bj980rkmpic3sc2llij6g0.apps.googleusercontent.com',
    messagingSenderId: '75536888095',
    projectId: 'todozoid',
    storageBucket: 'todozoid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz2uxI0XxbFeL4jzEV5DJlhifvwIa4c14',
    appId: '1:75536888095:ios:768fc4dda7cf188c01802a',
    messagingSenderId: '75536888095',
    projectId: 'todozoid',
    storageBucket: 'todozoid.appspot.com',
    androidClientId:
        '75536888095-rop0hk91ifl0qs53hp0dnafb207vgir6.apps.googleusercontent.com',
    iosClientId:
        '75536888095-juec3pf3arp2rv1psat4h943adl43r5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todozoid2',
  );
}
